id: P009101
initial_creation_type: ocr
source_metadata:
  id: bdr:W25586
  title: ཤཱཀྱ་མཆོག་ལྡན་གྱི་རྣམ་ཐར་ཞིབ་མོ་རྣམ་འབྱེད་
  author: ''
  volumes:
    4647f3c4740d4c8eac287240f62cabf9:
      image_group_id: I00KG03577
      title: ''
      volume_number: 1
      total_pages: 218
      base_file: v001.txt
