id: I4007BEBA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:15:29+00:00'
last_modified: '2022-06-08T08:37:29.574412+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25586
  title: ཤཱཀྱ་མཆོག་ལྡན་གྱི་རྣམ་ཐར་ཞིབ་མོ་རྣམ་འབྱེད་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    7AE7:
      image_group_id: I00KG03577
      title: ''
      total_pages: 218
      order: 1
      base_file: 7AE7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
